### ISSUE TITLE
my first PR for this plugin

### ISSUE THREAD

**Issue by cav71** [pelican-plugins/show-source#2]
That is

**Comment by kdeldycke** [comment]
I just imported your work in https://github.com/pelican-plugins/show-source/pull/3

**Comment by cav71** [comment]
Great thanks, I’ll work out of that forking using the GitHub pull requests.

I’ve also seen an invitation "@kdeldycke has invited you to collaborate on the
pelican-plugins/show-source repository” but the link seems not working.

What’s the best strategy to create a plugin test? Is there any skeleton template to use (I’ve seen webassests that has a rather good test suite)?

Thanks
